spring.application.name=kid-feed-app

spring.datasource.url=jdbc:postgresql://localhost:5432/kid_feed_app
spring.datasource.username=postgres
spring.datasource.password=Kdfmiaiao11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false